#!/usr/bin/python
# -*- coding: utf-8 -*-

"""モジュールの説明タイトル

     * ソースコードの一番始めに記載すること
     * importより前に記載する

Todo:
   TODOリストを記載
    * conf.pyの``sphinx.ext.todo`` を有効にしないと使用できない
    * conf.pyの``todo_include_todos = True``にしないと表示されない

"""

# standard modules

# third party modules

# original modules


# Define const value
# status
STATUS_PENDING = 0
STATUS_RUNNING = 1
STATUS_DONE = 2
STATUS_FAILED = 3

# phase
PHASE_TRAIN = 10
PHASE_VAL = 11
PHASE_TEST = 12

# type of evaluation index
INDEX_TYPE_AP = 20
INDEX_TYPE_MEAN_AP = 21

INDEX_TYPE_IOU = 22
INDEX_TYPE_MEAN_IOU = 23

INDEX_TYPE_ACCURACY = 24
INDEX_TYPE_MEAN_ACCURACY = 25

INDEX_TYPE_PRECISION = 26
INDEX_TYPE_MEAN_PRECISION = 27

INDEX_TYPE_RECALL = 28
INDEX_TYPE_MEAN_RECALL = 29

INDEX_TYPE_FALSE_POSITIVE_RATE = 30
INDEX_TYPE_MEAN_FALSE_POSITIVE_RATE = 31

INDEX_TYPE_F_MEASUER = 32
INDEX_TYPE_MEAN_F_MEASUER = 33

INDEX_TYPE_SPECIFICITY = 34
INDEX_TYPE_MEAN_SPECIFICITY = 35

INDEX_TYPE_AUC = 36
INDEX_TYPE_MEAN_AUC = 37

INDEX_TYPE_RMSE = 38
INDEX_TYPE_MAE = 39

INDEX_TYPE_R2 = 40

INDEX_TYPE_AIC = 41

INDEX_TYPE_F_LOSS = 42

INDEX_TYPE_NORMAL_CONTINUOUS = 43

#
TYPE_DIST_NOROMAL = 60
TYPE_DIST_UNIFORM = 61
TYPE_DIST_BERNOULI = 62
TYPE_DIST_BINOMICAL = 63
TYPE_DIST_CATEGORICAL = 64
TYPE_DIST_CAUCHY = 65
TYPE_DIST_HALFNORMAL = 66

TYPE_DATA_USE_INPUT = 90
TYPE_DATA_USE_GT = 91
TYPE_DATA_USE_OTHER = 92

TYPE_DATA_IMAGE = 100
TYPE_DATA_LABEL_IMAGE = 101
TYPE_DATA_CATEGORICAL = 102
TYPE_DATA_NUMERICAL = 103
TYPE_DATA_BBOX = 104
TYPE_DATA_POLYGON = 105

TYPE_VALUE_BOOL = 120
TYPE_VALUE_INT = 121
TYPE_VALUE_FLOAT = 122
TYPE_VALUE_CATEGORICAL = 123
TYPE_VALUE_STR = 124

ALL_TYPE_VALUE = {
    "bool": TYPE_VALUE_BOOL,
    "int": TYPE_VALUE_INT,
    "float": TYPE_VALUE_FLOAT,
    "categorical": TYPE_VALUE_CATEGORICAL,
    "str": TYPE_VALUE_STR
}

TYPE_SCALE_LINEAR = 130
TYPE_SCALE_LOG = 131
TYPE_SCALE_EXP = 132
TYPE_SCALE_X2 = 133
TYPE_SCALE_X3 = 134
TYPE_SCALE_XN = 135

ALL_TYPE_SCALE = {
    "linear" : TYPE_SCALE_LINEAR,
    "log" : TYPE_SCALE_LOG,
    "exp" : TYPE_SCALE_EXP,
    "x2" : TYPE_SCALE_X2,
    "x3" : TYPE_SCALE_X3,
    "xn" : TYPE_SCALE_XN
}



ALL_DIST_TYPE = [
    TYPE_DIST_NOROMAL,
    TYPE_DIST_UNIFORM,
    TYPE_DIST_BERNOULI,
    TYPE_DIST_BINOMICAL,
    TYPE_DIST_CATEGORICAL,
    TYPE_DIST_CAUCHY,
    TYPE_DIST_HALFNORMAL
]


# define all value list
ALL_STATUS = [
    STATUS_PENDING,
    STATUS_RUNNING,
    STATUS_DONE,
    STATUS_FAILED
]

ALL_PHASE = [
    PHASE_TRAIN,
    PHASE_VAL,
    PHASE_TEST
]

ALL_EVAL_INDEX_TYPE = [
    INDEX_TYPE_AP,
    INDEX_TYPE_MEAN_AP,
    INDEX_TYPE_IOU,
    INDEX_TYPE_MEAN_IOU,
    INDEX_TYPE_ACCURACY,
    INDEX_TYPE_MEAN_ACCURACY,
    INDEX_TYPE_PRECISION,
    INDEX_TYPE_MEAN_PRECISION,
    INDEX_TYPE_RECALL,
    INDEX_TYPE_MEAN_RECALL,
    INDEX_TYPE_FALSE_POSITIVE_RATE,
    INDEX_TYPE_MEAN_FALSE_POSITIVE_RATE,
    INDEX_TYPE_F_MEASUER,
    INDEX_TYPE_MEAN_F_MEASUER,
    INDEX_TYPE_SPECIFICITY,
    INDEX_TYPE_MEAN_SPECIFICITY,
    INDEX_TYPE_AUC,
    INDEX_TYPE_MEAN_AUC,
    INDEX_TYPE_RMSE,
    INDEX_TYPE_MAE,
    INDEX_TYPE_R2,
    INDEX_TYPE_AIC,
    INDEX_TYPE_F_LOSS
]